version: '3'
services:
    app:
        image: noeldemartin/vocab
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env
        networks:
            default:
                aliases:
                    - vocab

networks:
    default:
        name: nginx-agora
        external: true
