services:
  app:
    image: noeldemartin/vocab
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vocab

networks:
  default:
    name: nginx-agora-vocab
    external: true
