name: CI
on: [push]
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Install npm packages
        run: npm ci --no-audit
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Generate assets
        run: npm run build
      - name: Run Linting
        run: ./vendor/bin/pint --test
      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse
      - name: Run Tests
        run: php artisan test
