name: DockerHub
on: [push]
jobs:

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Install Node dependencies
        run: npm ci --no-audit
      - name: Generate assets
        run: npm run build
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/vocab:$(git rev-parse HEAD)
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vocab:$(git rev-parse HEAD)
