name: Kanjuro
on:
  push:
    branches:
      - 'main'

jobs:
  update-kanjuro:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update kanjuro branch
        run: ./.github/scripts/update-kanjuro.sh
